scoreboard objectives add x dummy
scoreboard objectives add y dummy
scoreboard objectives add z dummy
scoreboard players add @s x 0
scoreboard players add @s y 0
scoreboard players add @s z 0
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-4~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 3
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-5~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 4
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-6~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 5
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-7~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 6
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-8~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 7
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-9~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 8
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-10~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 9
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-11~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 10
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-12~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 11
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-13~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 12
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-14~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 13
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-15~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 14
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-16~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 15
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-17~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 16
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-18~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 17
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-19~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 18
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-20~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 19
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-21~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 20
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-22~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 21
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-23~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 22
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-24~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 23
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-25~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 24
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-26~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 25
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-27~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 26
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-28~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 27
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-29~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 28
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-30~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 29
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-31~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 30
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-32~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 31
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-33~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 32
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-34~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 33
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-35~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 34
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-36~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 35
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-37~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 36
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-38~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 37
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-39~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 38
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-40~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 39
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-41~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 40
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-42~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 41
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-43~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 42
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-44~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 43
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-45~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 44
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-46~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 45
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-47~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 46
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-48~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 47
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-49~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 48
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-50~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 49
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-51~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 50
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-52~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 51
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-53~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 52
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-54~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 53
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-55~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 54
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-56~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 55
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-57~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 56
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-58~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 57
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-59~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 58
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-60~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 59
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-61~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 60
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-62~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 61
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-63~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 62
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-64~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 63
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-65~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 64
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-66~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 65
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-67~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 66
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-68~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 67
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-69~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 68
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-70~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 69
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-71~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 70
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-72~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 71
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-73~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 72
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-74~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 73
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-75~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 74
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-76~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 75
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-77~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 76
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-78~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 77
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-79~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 78
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-80~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 79
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-81~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 80
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-82~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 81
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-83~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 82
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-84~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 83
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-85~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 84
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-86~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 85
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-87~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 86
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-88~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 87
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-89~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 88
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-90~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 89
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-91~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 90
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-92~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 91
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-93~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 92
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-94~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 93
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-95~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 94
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-96~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 95
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-97~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 96
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-98~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 97
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-99~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 98
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-100~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 99
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-101~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 100
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-102~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 101
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-103~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 102
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-104~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 103
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-105~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 104
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-106~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 105
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-107~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 106
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-108~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 107
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-109~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 108
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-110~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 109
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-111~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 110
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-112~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 111
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-113~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 112
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-114~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 113
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-115~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 114
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-116~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 115
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-117~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 116
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-118~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 117
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-119~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 118
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-120~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 119
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-121~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 120
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-122~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 121
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-123~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 122
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-124~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 123
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-125~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 124
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-126~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 125
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-127~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 126
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-128~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 127
execute @s ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ detect ~~-129~ se:green_elevator_omni_mk4  0 scoreboard players add @s[scores={y=0}] y 128
execute @s[scores={y=!0}] ~~~ detect ~~-1~ se:green_elevator_omni_mk4 0 execute @s ~~~ function OMNIMK4/tpDownOMNIMK4