scoreboard objectives add x dummy
scoreboard objectives add y dummy
scoreboard objectives add z dummy
scoreboard players add @s x 0
scoreboard players add @s y 0
scoreboard players add @s z 0
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~3~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 4
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-3 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -3
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-3 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -3
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~3 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 3
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~3~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 3
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-3~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -3
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~4~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 5
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-4 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -4
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-4 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -4
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~4 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 4
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~4~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 4
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-4~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -4
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~5~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 6
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-5 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -5
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-5 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -5
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~5 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 5
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~5~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 5
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-5~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -5
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~6~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 7
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-6 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -6
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-6 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -6
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~6 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 6
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~6~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 6
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-6~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -6
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~7~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 8
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-7 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -7
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-7 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -7
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~7 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 7
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~7~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 7
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-7~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -7
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~8~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 9
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-8 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -8
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-8 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -8
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~8 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 8
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~8~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 8
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-8~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -8
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~9~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 10
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-9 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -9
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-9 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -9
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~9 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 9
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~9~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 9
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-9~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -9
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~10~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 11
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-10 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -10
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-10 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -10
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~10 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 10
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~10~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 10
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-10~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -10
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~11~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 12
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-11 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -11
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-11 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -11
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~11 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 11
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~11~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 11
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-11~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -11
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~12~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 13
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-12 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -12
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-12 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -12
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~12 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 12
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~12~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 12
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-12~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -12
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~13~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 14
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-13 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -13
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-13 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -13
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~13 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 13
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~13~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 13
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-13~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -13
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~14~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 15
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-14 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -14
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-14 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -14
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~14 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 14
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~14~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 14
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-14~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -14
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~15~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 16
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-15 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -15
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-15 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -15
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~15 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 15
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~15~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 15
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-15~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -15
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~16~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 17
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-16 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -16
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-16 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -16
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~16 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 16
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~16~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 16
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-16~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -16
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~17~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 18
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-17 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -17
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-17 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -17
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~17 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 17
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~17~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 17
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-17~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -17
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~18~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 19
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-18 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -18
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-18 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -18
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~18 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 18
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~18~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 18
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-18~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -18
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~19~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 20
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-19 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -19
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-19 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -19
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~19 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 19
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~19~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 19
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-19~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -19
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~20~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 21
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-20 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -20
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-20 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -20
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~20 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 20
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~20~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 20
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-20~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -20
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~21~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 22
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-21 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -21
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-21 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -21
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~21 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 21
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~21~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 21
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-21~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -21
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~22~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 23
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-22 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -22
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-22 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -22
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~22 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 22
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~22~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 22
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-22~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -22
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~23~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 24
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-23 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -23
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-23 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -23
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~23 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 23
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~23~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 23
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-23~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -23
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~24~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 25
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-24 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -24
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-24 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -24
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~24 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 24
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~24~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 24
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-24~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -24
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~25~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 26
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-25 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -25
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-25 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -25
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~25 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 25
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~25~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 25
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-25~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -25
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~26~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 27
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-26 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -26
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-26 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -26
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~26 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 26
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~26~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 26
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-26~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -26
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~27~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 28
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-27 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -27
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-27 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -27
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~27 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 27
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~27~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 27
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-27~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -27
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~28~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 29
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-28 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -28
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-28 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -28
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~28 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 28
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~28~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 28
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-28~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -28
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~29~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 30
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-29 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -29
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-29 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -29
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~29 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 29
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~29~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 29
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-29~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -29
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~30~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 31
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-30 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -30
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-30 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -30
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~30 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 30
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~30~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 30
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-30~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -30
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~31~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 32
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-31 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -31
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-31 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -31
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~31 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 31
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~31~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 31
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-31~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -31
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~32~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 33
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-32 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -32
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-32 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -32
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~32 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 32
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~32~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 32
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-32~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -32
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~33~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 34
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-33 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -33
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-33 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -33
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~33 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 33
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~33~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 33
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-33~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -33
execute @s[scores={x=!0}] ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s ~~~ function OMNIMK3/tpOMNIMK3
execute @s[scores={y=!0}] ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s ~~~ function OMNIMK3/tpOMNIMK3
execute @s[scores={z=!0}] ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s ~~~ function OMNIMK3/tpOMNIMK3
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~34 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 34
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~34~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 34
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-34~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -34
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~35~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 36
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-35 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -35
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-35 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -35
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~35 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 35
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~35~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 35
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-35~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -35
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~36~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 37
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-36 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -36
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-36 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -36
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~36 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 36
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~36~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 36
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-36~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -36
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~37~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 38
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-37 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -37
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-37 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -37
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~37 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 37
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~37~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 37
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-37~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -37
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~38~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 39
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-38 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -38
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-38 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -38
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~38 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 38
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~38~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 38
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-38~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -38
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~39~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 40
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-39 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -39
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-39 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -39
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~39 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 39
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~39~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 39
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-39~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -39
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~40~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 41
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-40 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -40
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-40 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -40
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~40 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 40
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~40~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 40
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-40~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -40
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~41~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 42
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-41 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -41
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-41 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -41
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~41 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 41
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~41~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 41
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-41~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -41
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~42~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 43
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-42 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -42
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-42 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -42
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~42 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 42
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~42~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 42
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-42~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -42
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~43~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 44
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-43 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -43
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-43 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -43
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~43 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 43
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~43~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 43
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-43~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -43
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~44~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 45
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-44 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -44
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-44 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -44
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~44 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 44
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~44~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 44
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-44~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -44
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~45~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 46
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-45 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -45
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-45 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -45
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~45 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 45
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~45~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 45
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-45~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -45
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~46~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 47
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-46 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -46
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-46 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -46
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~46 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 46
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~46~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 46
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-46~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -46
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~47~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 48
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-47 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -47
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-47 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -47
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~47 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 47
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~47~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 47
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-47~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -47
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~48~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 49
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-48 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -48
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-48 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -48
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~48 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 48
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~48~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 48
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-48~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -48
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~49~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 50
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-49 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -49
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-49 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -49
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~49 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 49
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~49~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 49
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-49~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -49
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~50~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 51
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-50 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -50
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-50 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -50
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~50 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 50
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~50~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 50
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-50~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -50
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~51~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 52
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-51 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -51
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-51 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -51
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~51 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 51
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~51~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 51
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-51~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -51
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~52~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 53
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-52 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -52
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-52 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -52
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~52 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 52
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~52~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 52
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-52~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -52
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~53~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 54
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-53 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -53
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-53 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -53
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~53 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 53
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~53~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 53
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-53~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -53
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~54~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 55
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-54 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -54
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-54 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -54
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~54 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 54
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~54~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 54
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-54~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -54
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~55~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 56
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-55 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -55
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-55 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -55
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~55 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 55
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~55~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 55
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-55~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -55
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~56~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 57
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-56 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -56
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-56 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -56
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~56 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 56
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~56~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 56
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-56~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -56
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~57~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 58
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-57 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -57
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-57 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -57
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~57 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 57
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~57~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 57
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-57~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -57
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~58~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 59
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-58 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -58
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-58 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -58
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~58 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 58
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~58~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 58
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-58~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -58
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~59~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 60
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-59 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -59
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-59 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -59
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~59 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 59
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~59~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 59
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-59~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -59
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~60~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 61
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-60 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -60
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-60 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -60
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~60 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 60
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~60~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 60
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-60~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -60
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~61~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 62
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-61 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -61
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-61 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -61
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~61 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 61
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~61~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 61
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-61~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -61
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~62~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 63
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-62 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -62
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-62 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -62
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~62 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 62
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~62~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 62
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-62~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -62
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~63~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 64
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-63 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -63
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-63 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -63
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~63 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 63
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~63~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 63
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-63~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -63
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[rx=-45] ~~~ detect ~~64~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={y=0}] y 65
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-64 se:yellow_elevator_omni_mk3 0  scoreboard players add @s[scores={z=0}] z -64
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-64 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z -64
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~64 se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={z=0}] z 64
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=-45,rym=-145] ~~~ detect ~64~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x 64
execute @s ~~~ detect ~~-1~ se:yellow_elevator_omni_mk3 0 execute @s[ry=145,rym=45] ~~~ detect ~-64~-1~ se:yellow_elevator_omni_mk3 0 scoreboard players add @s[scores={x=0}] x -64