scoreboard objectives add x dummy
scoreboard objectives add y dummy
scoreboard objectives add z dummy
scoreboard players add @s x 0
scoreboard players add @s y 0
scoreboard players add @s z 0
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-4~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 3
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-5~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 4
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-6~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 5
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-7~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 6
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-8~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 7
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-9~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 8
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-10~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 9
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-11~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 10
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-12~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 11
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-13~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 12
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-14~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 13
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-15~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 14
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-16~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 15
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-17~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 16
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-18~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 17
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-19~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 18
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-20~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 19
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-21~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 20
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-22~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 21
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-23~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 22
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-24~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 23
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-25~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 24
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-26~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 25
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-27~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 26
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-28~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 27
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-29~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 28
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-30~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 29
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-31~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 30
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-32~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 31
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-33~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 32
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-34~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 33
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-35~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 34
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-36~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 35
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-37~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 36
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-38~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 37
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-39~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 38
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-40~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 39
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-41~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 40
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-42~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 41
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-43~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 42
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-44~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 43
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-45~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 44
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-46~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 45
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-47~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 46
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-48~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 47
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-49~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 48
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-50~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 49
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-51~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 50
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-52~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 51
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-53~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 52
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-54~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 53
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-55~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 54
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-56~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 55
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-57~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 56
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-58~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 57
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-59~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 58
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-60~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 59
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-61~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 60
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-62~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 61
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-63~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 62
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-64~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 63
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-65~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 64
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-66~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 65
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-67~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 66
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-68~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 67
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-69~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 68
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-70~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 69
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-71~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 70
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-72~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 71
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-73~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 72
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-74~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 73
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-75~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 74
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-76~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 75
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-77~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 76
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-78~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 77
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-79~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 78
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-80~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 79
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-81~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 80
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-82~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 81
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-83~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 82
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-84~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 83
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-85~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 84
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-86~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 85
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-87~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 86
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-88~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 87
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-89~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 88
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-90~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 89
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-91~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 90
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-92~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 91
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-93~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 92
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-94~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 93
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-95~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 94
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-96~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 95
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-97~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 96
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-98~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 97
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-99~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 98
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-100~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 99
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-101~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 100
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-102~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 101
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-103~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 102
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-104~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 103
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-105~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 104
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-106~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 105
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-107~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 106
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-108~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 107
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-109~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 108
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-110~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 109
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-111~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 110
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-112~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 111
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-113~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 112
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-114~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 113
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-115~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 114
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-116~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 115
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-117~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 116
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-118~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 117
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-119~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 118
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-120~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 119
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-121~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 120
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-122~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 121
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-123~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 122
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-124~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 123
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-125~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 124
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-126~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 125
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-127~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 126
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-128~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 127
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-129~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 128
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-130~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 129
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-131~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 130
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-132~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 131
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-133~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 132
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-134~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 133
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-135~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 134
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-136~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 135
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-137~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 136
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-138~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 137
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-139~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 138
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-140~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 139
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-141~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 140
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-142~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 141
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-143~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 142
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-144~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 143
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-145~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 144
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-146~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 145
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-147~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 146
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-148~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 147
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-149~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 148
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-150~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 149
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-151~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 150
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-152~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 151
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-153~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 152
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-154~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 153
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-155~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 154
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-156~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 155
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-157~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 156
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-158~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 157
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-159~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 158
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-160~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 159
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-161~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 160
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-162~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 161
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-163~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 162
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-164~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 163
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-165~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 164
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-166~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 165
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-167~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 166
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-168~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 167
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-169~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 168
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-170~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 169
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-171~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 170
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-172~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 171
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-173~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 172
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-174~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 173
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-175~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 174
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-176~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 175
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-177~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 176
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-178~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 177
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-179~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 178
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-180~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 179
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-181~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 180
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-182~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 181
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-183~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 182
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-184~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 183
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-185~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 184
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-186~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 185
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-187~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 186
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-188~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 187
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-189~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 188
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-190~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 189
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-191~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 190
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-192~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 191
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-193~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 192
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-194~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 193
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-195~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 194
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-196~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 195
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-197~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 196
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-198~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 197
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-199~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 198
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-200~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 199
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-201~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 200
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-202~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 201
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-203~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 202
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-204~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 203
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-205~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 204
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-206~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 205
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-207~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 206
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-208~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 207
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-209~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 208
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-210~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 209
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-211~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 210
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-212~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 211
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-213~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 212
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-214~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 213
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-215~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 214
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-216~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 215
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-217~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 216
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-218~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 217
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-219~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 218
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-220~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 219
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-221~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 220
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-222~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 221
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-223~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 222
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-224~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 223
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-225~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 224
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-226~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 225
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-227~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 226
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-228~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 227
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-229~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 228
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-230~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 229
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-231~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 230
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-232~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 231
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-233~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 232
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-234~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 233
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-235~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 234
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-236~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 235
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-237~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 236
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-238~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 237
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-239~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 238
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-240~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 239
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-241~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 240
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-242~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 241
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-243~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 242
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-244~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 243
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-245~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 244
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-246~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 245
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-247~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 246
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-248~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 247
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-249~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 248
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-250~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 249
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-251~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 250
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-252~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 251
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-253~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 252
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-254~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 253
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-255~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 254
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-256~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 255
execute @s ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ detect ~~-257~ se:purple_elevator_omega  0 scoreboard players add @s[scores={y=0}] y 256
execute @s[scores={y=!0}] ~~~ detect ~~-1~ se:purple_elevator_omega 0 execute @s ~~~ function OMEGA/tpDownOMEGA