scoreboard objectives add x dummy
scoreboard objectives add y dummy
scoreboard objectives add z dummy
scoreboard players add @s x 0
scoreboard players add @s y 0
scoreboard players add @s z 0
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~3~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 4
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-3 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -3
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-3 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -3
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~3 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 3
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~3~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 3
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-3~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -3
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~4~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 5
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-4 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -4
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-4 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -4
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~4 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 4
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~4~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 4
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-4~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -4
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~5~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 6
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-5 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -5
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-5 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -5
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~5 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 5
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~5~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 5
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-5~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -5
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~6~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 7
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-6 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -6
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-6 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -6
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~6 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 6
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~6~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 6
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-6~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -6
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~7~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 8
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-7 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -7
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-7 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -7
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~7 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 7
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~7~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 7
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-7~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -7
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~8~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 9
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-8 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -8
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-8 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -8
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~8 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 8
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~8~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 8
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-8~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -8
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~9~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 10
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-9 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -9
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-9 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -9
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~9 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 9
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~9~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 9
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-9~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -9
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~10~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 11
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-10 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -10
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-10 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -10
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~10 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 10
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~10~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 10
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-10~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -10
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~11~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 12
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-11 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -11
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-11 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -11
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~11 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 11
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~11~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 11
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-11~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -11
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~12~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 13
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-12 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -12
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-12 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -12
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~12 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 12
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~12~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 12
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-12~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -12
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~13~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 14
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-13 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -13
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-13 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -13
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~13 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 13
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~13~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 13
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-13~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -13
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~14~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 15
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-14 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -14
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-14 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -14
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~14 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 14
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~14~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 14
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-14~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -14
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~15~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 16
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-15 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -15
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-15 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -15
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~15 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 15
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~15~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 15
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-15~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -15
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~16~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 17
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-16 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -16
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-16 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -16
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~16 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 16
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~16~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 16
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-16~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -16
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~17~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 18
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-17 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -17
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-17 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -17
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~17 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 17
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~17~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 17
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-17~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -17
execute @s[scores={x=!0}] ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s ~~~ function OMNIMK2/tpOMNIMK2
execute @s[scores={y=!0}] ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s ~~~ function OMNIMK2/tpOMNIMK2
execute @s[scores={z=!0}] ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s ~~~ function OMNIMK2/tpOMNIMK2
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~18 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 18
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~18~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 18
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-18~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -18
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~19~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 20
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-19 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -19
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-19 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -19
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~19 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 19
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~19~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 19
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-19~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -19
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~20~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 21
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-20 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -20
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-20 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -20
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~20 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 20
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~20~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 20
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-20~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -20
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~21~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 22
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-21 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -21
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-21 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -21
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~21 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 21
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~21~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 21
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-21~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -21
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~22~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 23
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-22 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -22
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-22 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -22
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~22 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 22
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~22~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 22
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-22~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -22
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~23~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 24
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-23 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -23
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-23 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -23
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~23 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 23
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~23~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 23
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-23~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -23
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~24~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 25
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-24 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -24
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-24 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -24
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~24 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 24
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~24~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 24
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-24~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -24
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~25~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 26
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-25 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -25
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-25 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -25
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~25 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 25
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~25~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 25
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-25~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -25
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~26~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 27
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-26 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -26
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-26 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -26
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~26 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 26
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~26~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 26
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-26~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -26
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~27~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 28
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-27 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -27
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-27 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -27
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~27 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 27
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~27~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 27
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-27~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -27
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~28~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 29
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-28 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -28
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-28 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -28
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~28 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 28
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~28~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 28
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-28~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -28
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~29~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 30
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-29 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -29
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-29 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -29
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~29 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 29
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~29~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 29
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-29~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -29
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~30~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 31
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-30 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -30
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-30 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -30
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~30 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 30
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~30~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 30
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-30~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -30
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~31~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 32
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-31 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -31
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-31 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -31
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~31 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 31
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~31~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 31
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-31~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -31
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[rx=-45] ~~~ detect ~~32~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={y=0}] y 33
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-145,rym=-180] ~~~ detect ~~-1~-32 se:purple_elevator_omni_mk2 0  scoreboard players add @s[scores={z=0}] z -32
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=180,rym=145] ~~~ detect ~~-1~-32 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z -32
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=45,rym=-45] ~~~ detect ~~-1~32 se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={z=0}] z 32
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=-45,rym=-145] ~~~ detect ~32~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x 32
execute @s ~~~ detect ~~-1~ se:purple_elevator_omni_mk2 0 execute @s[ry=145,rym=45] ~~~ detect ~-32~-1~ se:purple_elevator_omni_mk2 0 scoreboard players add @s[scores={x=0}] x -32